var nodemailer = require('nodemailer');

function sendMail(subject,content,contentHtml,to,cc){
var transporter = nodemailer.createTransport({
    host: "box.sinely.com",
    port: 587,
    auth: {
      user: "contact@sinely.com", //generated by Mailtrap
      pass: "Badrafaf123" //generated by Mailtrap
    },
    tls: {
        rejectUnauthorized: false
    }
  });

  let mailOptions = {
    from: 'contact@sinely.com',
    to: to,
    subject: subject,
    cc:cc,
    text: content,
    html:contentHtml
};

transporter.sendMail(mailOptions, function(e, r) {
    if (e) {
      console.log("Error while sending mail",e);}
    else {
      console.log("Mail sent with success",r);
        }
    transporter.close();
    });
}


module.exports = {
 
     sendMail,
  };