version: '3'
services:
  postgres:
    image: postgres
    container_name: sm_postgres_sinely
    environment:
      POSTGRES_USER: 'sinely'
      POSTGRES_PASSWORD: 'sinely123'
      POSTGRES_DB: 'sinely'
    ports:
      - 5433:5432
    volumes:
      - postgresql-sm-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: sm_redis_sinely
    ports:
      - 6379:6379
  haproxy:
    image: haproxy:1.9-alpine
    container_name: sm_haproxy_sinely
    ports:
      - 81:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
volumes:
  postgresql-sm-data:
